language: node_js
node_js:
  - 10
notifications:
  email: false
git:
  depth: false
branches:
  only:
  - gh-pages
cache: yarn
install: yarn
script:
  - yarn run dist
  - cp robots.txt ./dist/
  - node scripts/sitemap.js
  - node scripts/upload.js ${qiniu_sk}
  - git checkout master
  - cp -r ./dist/* ./
  - bash ./build.sh
